version: '3.8'

services:
  web:
    image: python
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/local/bin/start.sh
    container_name: cpa-web
    restart: always
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db

  db:
    image: postgres:15
    container_name: cpa-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    image: nginx
    build: ./nginx
    container_name: cpa-nginx
    domainname: 'capstone-projects-allocator'
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    container_name: cpa-redis

  celery_worker:
    image: celery
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpa-celery
    command: /usr/local/bin/start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db

volumes:
  postgres-data:
