# Generated by Django 4.2.4 on 2023-08-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='area',
        ),
        migrations.RemoveField(
            model_name='student',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
