# Generated by Django 4.2.4 on 2023-08-04 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=50)),
                ('preference_submission_start', models.DateTimeField(blank=True, null=True)),
                ('preference_submission_end', models.DateTimeField(blank=True, null=True)),
                ('minimum_preference_limit', models.IntegerField(blank=True, null=True)),
                ('manager', models.ForeignKey(limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='enrolled_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('code', 'year', 'semester'), name='core_unit_unique'),
        ),
    ]
