# Generated by Django 4.2.4 on 2023-08-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_allocated_pref',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_allocating',
            field=models.BooleanField(default=False),
        ),
    ]
