# Generated by Django 4.2.4 on 2023-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_area_project_area_student_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='unit',
            name='maximum_preference_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(check=models.Q(('minimum_preference_limit__isnull', True), ('maximum_preference_limit__isnull', True), ('minimum_preference_limit', models.F('maximum_preference_limit')), ('minimum_preference_limit__lt', models.F('maximum_preference_limit')), _connector='OR'), name='minimum_preference_limit_lt_max', violation_error_message='The minimum preference limit must be less than or equal to the maximum preference limit.'),
        ),
    ]
