# Generated by Django 4.2.4 on 2023-08-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_avg_allocated_pref_unit_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='assigned_preference_rank',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
