# Generated by Django 4.2.4 on 2023-08-04 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_project_core_project_rank_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_preferences', to='core.project')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_preferences', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_project_preferences', to='core.unit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectpreference',
            constraint=models.UniqueConstraint(fields=('student', 'unit', 'rank'), name='core_projectpreference_rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectpreference',
            constraint=models.UniqueConstraint(fields=('student', 'unit', 'project'), name='core_projectpreference_project_unique'),
        ),
    ]
