# Generated by Django 4.2.4 on 2023-08-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrolledstudent_assigned_preference_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='allocation_status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('AL', 'Currently Allocating'), ('FA', 'Allocation Failed'), ('OP', 'Optimal'), ('FS', 'Feasible'), ('IF', 'Proven Infeasible'), ('UN', 'Proven Unbounded'), ('AB', 'Abnormal'), ('MI', 'Model Invalid')], default='NS', max_length=2),
        ),
    ]
