# Generated by Django 4.2.4 on 2023-08-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpreference',
            options={'ordering': ['unit_id', 'student_id', 'rank']},
        ),
    ]
