# Generated by Django 4.2.5 on 2023-09-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allocated_preference_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='allocated_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_students', to='core.project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.area'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='allocation_status',
            field=models.CharField(blank=True, choices=[('OP', 'Successful (Optimal)'), ('FS', 'Successful (Feasible)'), ('IF', 'Failed (Proven Infeasible)'), ('UN', 'Failed (Proven Unbounded)'), ('AB', 'Failed (Abnormal)'), ('MI', 'Failed (Model Invalid)'), ('NO', 'Failed (Not Solved)')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
