# Generated by Django 4.2.4 on 2023-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_unit_allocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_allocating',
        ),
        migrations.AlterField(
            model_name='unit',
            name='allocation_status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('AL', 'Currently Allocating'), ('OP', 'Allocation Successful - Optimal'), ('FS', 'Allocation Successful - Feasible'), ('IF', 'Allocation Failed - Proven Infeasible'), ('UN', 'Allocation Failed - Proven Unbounded'), ('AB', 'Allocation Failed - Abnormal'), ('MI', 'Allocation Failed - Model Invalid'), ('NO', 'Allocation Failed - Not Solved')], default='NS', max_length=2),
        ),
    ]
