# Generated by Django 4.2.5 on 2023-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_allocated_preference_rank_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='core_student_unique',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_id', 'unit'), name='core_student_unique_id'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('user', 'unit'), name='core_student_unique_user'),
        ),
    ]
