# Generated by Django 4.2.4 on 2023-08-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_unit_is_allocating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='allocation_status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('AL', 'Currently Allocating'), ('OP', 'Successful (Optimal)'), ('FS', 'Successful (Feasible)'), ('IF', 'Failed (Proven Infeasible)'), ('UN', 'Failed (Proven Unbounded)'), ('AB', 'Failed (Abnormal)'), ('MI', 'Failed (Model Invalid)'), ('NO', 'Failed (Not Solved)')], default='NS', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('min_students__isnull', True), ('max_students__isnull', True), ('min_students__lt', models.F('max_students')), _connector='OR'), name='min_lt_max'),
        ),
    ]
