# Generated by Django 4.2.5 on 2023-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_student_core_student_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['unit', 'number']},
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
