# Generated by Django 4.2.4 on 2023-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_unit_students_enrolledstudent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrolledstudent',
            constraint=models.UniqueConstraint(fields=('student_id', 'unit'), name='core_enrolledstudent_unique'),
        ),
    ]
