# Generated by Django 4.2.4 on 2023-08-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unit_allocation_status_project_min_lt_max'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='min_lt_max',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('min_students__isnull', True), ('max_students__isnull', True), ('min_students__lte', models.F('max_students')), _connector='OR'), name='min_lte_max', violation_error_message='The minimum number of students must not be less than the maximum.'),
        ),
    ]
