# Generated by Django 4.2.4 on 2023-08-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enrolledstudent_core_enrolledstudent_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledstudent',
            options={'ordering': ['student_id']},
        ),
    ]
