# Generated by Django 4.2.5 on 2023-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_options_alter_project_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['unit', 'identifier']},
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='core_project_rank_unique',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='number',
            new_name='identifier',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('unit', 'identifier'), name='core_project_rank_unique', violation_error_message='Each project in a unit must have a unique ID. A project with that ID is already included in this unit.'),
        ),
    ]
