# Generated by Django 4.2.4 on 2023-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_project_min_lt_max_project_min_lte_max'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='core_project_rank_unique',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='min_lte_max',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('unit', 'number'), name='core_project_rank_unique', violation_error_message='Each project in a unit must have a unique number. A project with that number is already included in this unit.'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('min_students__isnull', True), ('max_students__isnull', True), ('min_students__lte', models.F('max_students')), _connector='OR'), name='min_lte_max', violation_error_message='The minimum number of students for a project must not be less than the maximum number of students.'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(check=models.Q(('preference_submission_start__isnull', True), ('preference_submission_end__isnull', True), ('preference_submission_start__lt', models.F('preference_submission_end')), _connector='OR'), name='preference_submission_start_lt_end', violation_error_message='The preference submission end must be after the preference submission start.'),
        ),
    ]
