# Generated by Django 4.2.4 on 2023-08-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_project_options_alter_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['code', 'name']},
        ),
    ]
