# Generated by Django 4.2.5 on 2023-09-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_student_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='core_unit_unique',
        ),
        migrations.AlterField(
            model_name='unit',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('manager', 'code', 'year', 'semester'), name='core_unit_unique'),
        ),
    ]
