# Generated by Django 4.2.5 on 2023-09-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_unit_core_unit_unique_alter_unit_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_allocating',
        ),
        migrations.AddField(
            model_name='unit',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery ID for the Task that was run', max_length=255, null=True, unique=True, verbose_name='Task ID'),
        ),
        migrations.AddField(
            model_name='unit',
            name='task_name',
            field=models.CharField(blank=True, choices=[('ALLOC', 'Start Allocation'), ('EMALL', 'Email Allocation Results'), ('EPREF', 'Email Preferences List'), ('UPROJ', 'Upload Projects List'), ('USTUD', 'Upload Students List'), ('UPREF', 'Upload Preferences List')], help_text='Name of the Task which was run', max_length=5, null=True, verbose_name='Task Name'),
        ),
    ]
