# Generated by Django 4.2.5 on 2023-10-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('core', '0013_remove_unit_is_allocating_unit_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='celery_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='django_celery_results.taskresult'),
        ),
    ]
