# Generated by Django 4.2.5 on 2023-10-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unit_celery_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='task_name',
        ),
    ]
