# Generated by Django 4.2.6 on 2023-10-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('core', '0015_remove_unit_task_id_remove_unit_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='celery_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='django_celery_results.taskresult'),
        ),
    ]
